#!/usr/bin/env bash
# Deploy this Vite static site to a single Ubuntu server.
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
DEFAULTS_FILE="$SCRIPT_DIR/defaults.conf"
CONFIG_FILE=""
NON_INTERACTIVE=false
VALIDATE_ONLY=false

usage() {
  cat <<'EOF'
Usage:
  sudo bash deploy/ubuntu/deploy.sh
  sudo bash deploy/ubuntu/deploy.sh --config /etc/reborn-snake.env --non-interactive
  bash deploy/ubuntu/deploy.sh --config ./server.env --validate-config

First run prompts for the Git repository, branch, domain, deployment directory and HTTPS.
The generated configuration is saved under /etc and can be reused for later deployments.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config) CONFIG_FILE="${2:?--config needs a path}"; shift 2 ;;
    --non-interactive) NON_INTERACTIVE=true; shift ;;
    --validate-config) VALIDATE_ONLY=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) printf 'Unknown option: %s\n' "$1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ $EUID -ne 0 && $VALIDATE_ONLY != true ]]; then
  sudo_args=(bash "$0")
  if [[ -n $CONFIG_FILE ]]; then
    sudo_args+=(--config "$CONFIG_FILE")
  fi
  if [[ $NON_INTERACTIVE == true ]]; then
    sudo_args+=(--non-interactive)
  fi
  if [[ $VALIDATE_ONLY == true ]]; then
    sudo_args+=(--validate-config)
  fi
  exec sudo --preserve-env=PATH "${sudo_args[@]}"
fi

# shellcheck source=defaults.conf
source "$DEFAULTS_FILE"

die() { printf 'Error: %s\n' "$*" >&2; exit 1; }
info() { printf '\n==> %s\n' "$*"; }

prompt() {
  local variable="$1" label="$2" default="$3" value
  if [[ $NON_INTERACTIVE == true ]]; then
    return
  fi
  read -r -p "$label [$default]: " value
  printf -v "$variable" '%s' "${value:-$default}"
}

validate_config() {
  [[ ${GIT_REPOSITORY:-} ]] || die 'GIT_REPOSITORY must not be empty.'
  [[ ${GIT_BRANCH:-} ]] || die 'GIT_BRANCH must not be empty.'
  [[ ${APP_NAME:-} =~ ^[a-zA-Z0-9][a-zA-Z0-9-]*$ ]] || die 'APP_NAME may contain letters, numbers and hyphens only.'
  [[ ${DEPLOY_ROOT:-} == /* ]] || die 'DEPLOY_ROOT must be an absolute path.'
  [[ ${HTTP_PORT:-} =~ ^[0-9]+$ ]] && (( HTTP_PORT >= 1 && HTTP_PORT <= 65535 )) || die 'HTTP_PORT must be 1-65535.'
  [[ ${DISABLE_DEFAULT_NGINX_SITE:-} == true || ${DISABLE_DEFAULT_NGINX_SITE:-} == false ]] || die 'DISABLE_DEFAULT_NGINX_SITE must be true or false.'
  [[ -z ${DOMAIN_NAME:-} || ${DOMAIN_NAME:-} =~ ^[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?$ ]] || die 'DOMAIN_NAME must be one hostname without a protocol or path.'
  [[ ${ENABLE_HTTPS:-} == true || ${ENABLE_HTTPS:-} == false ]] || die 'ENABLE_HTTPS must be true or false.'
  if [[ $ENABLE_HTTPS == true ]]; then
    [[ ${DOMAIN_NAME:-} ]] || die 'DOMAIN_NAME is required when HTTPS is enabled.'
    [[ ${LETSENCRYPT_EMAIL:-} == *@*.* ]] || die 'LETSENCRYPT_EMAIL is required when HTTPS is enabled.'
  fi
}

write_config() {
  local target="$1"
  umask 077
  mkdir -p "$(dirname -- "$target")"
  {
    printf '# Generated by deploy/ubuntu/deploy.sh. Edit values, then rerun with --config.\n'
    printf 'NODE_MAJOR=%q\nPNPM_VERSION=%q\nAPP_NAME=%q\nDEPLOY_ROOT=%q\nHTTP_PORT=%q\nDISABLE_DEFAULT_NGINX_SITE=%q\nASSET_CACHE_DURATION=%q\n' \
      "$NODE_MAJOR" "$PNPM_VERSION" "$APP_NAME" "$DEPLOY_ROOT" "$HTTP_PORT" "$DISABLE_DEFAULT_NGINX_SITE" "$ASSET_CACHE_DURATION"
    printf 'GIT_REPOSITORY=%q\nGIT_BRANCH=%q\nDOMAIN_NAME=%q\nENABLE_HTTPS=%q\nLETSENCRYPT_EMAIL=%q\n' \
      "$GIT_REPOSITORY" "$GIT_BRANCH" "$DOMAIN_NAME" "$ENABLE_HTTPS" "$LETSENCRYPT_EMAIL"
  } > "$target"
  chmod 600 "$target"
}

if [[ -n $CONFIG_FILE ]]; then
  [[ -f $CONFIG_FILE ]] || die "Config file does not exist: $CONFIG_FILE"
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
else
  prompt GIT_REPOSITORY 'Git repository URL (HTTPS or SSH)' ''
  prompt GIT_BRANCH 'Git branch or tag' 'main'
  prompt DOMAIN_NAME 'Domain name (leave blank to use server IP)' ''
  prompt DEPLOY_ROOT 'Static-file deployment directory' "$DEPLOY_ROOT"
  prompt APP_NAME 'Application name' "$APP_NAME"
  prompt HTTP_PORT 'Nginx HTTP port' "$HTTP_PORT"
  if [[ -z $DOMAIN_NAME && $HTTP_PORT == 80 ]]; then
    prompt DISABLE_DEFAULT_NGINX_SITE 'Disable Ubuntu default Nginx site for IP access? (true/false)' "$DISABLE_DEFAULT_NGINX_SITE"
  else
    DISABLE_DEFAULT_NGINX_SITE=false
  fi
  if [[ -n $DOMAIN_NAME ]]; then
    prompt ENABLE_HTTPS 'Enable Lets Encrypt HTTPS? (true/false)' 'true'
    if [[ $ENABLE_HTTPS == true ]]; then
      prompt LETSENCRYPT_EMAIL 'Lets Encrypt notification email' ''
    else
      LETSENCRYPT_EMAIL=''
    fi
  else
    ENABLE_HTTPS=false
    LETSENCRYPT_EMAIL=''
  fi
  CONFIG_FILE="/etc/${APP_NAME}.env"
fi

validate_config
if [[ $VALIDATE_ONLY == true ]]; then
  info 'Configuration is valid'
  exit 0
fi
write_config "$CONFIG_FILE"

ensure_packages() {
  info 'Checking Ubuntu packages'
  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y ca-certificates curl git nginx

  if ! command -v node >/dev/null 2>&1 || [[ "$(node -p 'process.versions.node.split(`.`)[0]')" != "$NODE_MAJOR" ]]; then
    info "Installing Node.js ${NODE_MAJOR}.x"
    curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash -
    apt-get install -y nodejs
  fi

  corepack enable
  corepack prepare "pnpm@${PNPM_VERSION}" --activate
}

check_ubuntu() {
  [[ -r /etc/os-release ]] || die 'Cannot identify the operating system; Ubuntu is required.'
  # shellcheck disable=SC1091
  source /etc/os-release
  [[ ${ID:-} == ubuntu ]] || die "This script supports Ubuntu only; detected: ${PRETTY_NAME:-unknown}."
  command -v systemctl >/dev/null 2>&1 || die 'systemd is required to run Nginx.'
}

checkout_and_build() {
  local source_dir="/opt/${APP_NAME}/source"
  info 'Checking out and building the application'
  mkdir -p "$(dirname -- "$source_dir")"
  if [[ -d "$source_dir/.git" ]]; then
    git -C "$source_dir" remote set-url origin "$GIT_REPOSITORY"
    git -C "$source_dir" fetch --tags --prune origin
    git -C "$source_dir" checkout --force "$GIT_BRANCH"
    git -C "$source_dir" reset --hard "origin/$GIT_BRANCH" 2>/dev/null || true
  else
    [[ ! -e $source_dir ]] || die "Source directory exists but is not a Git checkout: $source_dir"
    git clone --branch "$GIT_BRANCH" --depth 1 "$GIT_REPOSITORY" "$source_dir"
  fi
  pnpm --dir "$source_dir" install --frozen-lockfile
  pnpm --dir "$source_dir" build
  [[ -f "$source_dir/dist/index.html" ]] || die 'Build did not create dist/index.html.'
  SOURCE_DIR="$source_dir"
}

publish_build() {
  local releases_dir="${DEPLOY_ROOT}/releases" release_dir
  release_dir="${releases_dir}/$(date +%Y%m%d%H%M%S)"
  info "Publishing build to $release_dir"
  mkdir -p "$release_dir"
  cp -a "$SOURCE_DIR/dist/." "$release_dir/"
  ln -sfn "$release_dir" "${DEPLOY_ROOT}/current"
}

configure_nginx() {
  local site_file="/etc/nginx/sites-available/${APP_NAME}" server_name
  server_name="${DOMAIN_NAME:-_}"
  info 'Writing and validating Nginx configuration'
  cat > "$site_file" <<EOF
server {
    listen ${HTTP_PORT};
    listen [::]:${HTTP_PORT};
    server_name ${server_name};

    root ${DEPLOY_ROOT}/current;
    index index.html;

    location /assets/ {
        try_files \$uri =404;
        expires ${ASSET_CACHE_DURATION};
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files \$uri \$uri/ /index.html;
    }
}
EOF
  ln -sfn "$site_file" "/etc/nginx/sites-enabled/${APP_NAME}"
  if [[ $DISABLE_DEFAULT_NGINX_SITE == true && -L /etc/nginx/sites-enabled/default ]]; then
    rm /etc/nginx/sites-enabled/default
  fi
  nginx -t
  systemctl enable --now nginx
  systemctl reload nginx
}

enable_https() {
  [[ $ENABLE_HTTPS == true ]] || return
  [[ $HTTP_PORT == 80 ]] || die 'Lets Encrypt requires HTTP_PORT=80 for this script.'
  info 'Installing and configuring Lets Encrypt certificate'
  apt-get install -y certbot python3-certbot-nginx
  certbot --nginx --non-interactive --agree-tos --redirect --email "$LETSENCRYPT_EMAIL" -d "$DOMAIN_NAME"
}

check_ubuntu
ensure_packages
checkout_and_build
publish_build
configure_nginx
enable_https

info 'Deployment complete'
if [[ -n $DOMAIN_NAME ]]; then
  printf 'Open: %s://%s\n' "$([[ $ENABLE_HTTPS == true ]] && printf https || printf http)" "$DOMAIN_NAME"
else
  printf 'Open: http://<this-server-ip>:%s\n' "$HTTP_PORT"
fi
printf 'Reusable config: %s\n' "$CONFIG_FILE"
